### PR TITLE
Explicitly export names in `jaxtyping.*`

### PR DESCRIPTION
**Pull request by brentyi**
Hi @patrick-kidger!

When using the current version of `jaxtyping`, writing:
```python
from jaxtyping import Float
```

Results in a pyright error:
```
reportPrivateImportUsage: "Float" is not exported from module "jaxtyping"
Import from "jaxtyping.array_types" instead
```

This PR just explicitly exports names in `__init__.py` and `array_types.py`. It's helpful for making `jaxtyping` more usable for anybody running `pyright` or `pylance`: it suppresses the error and fixes things like tab completion and auto-import for names in `jaxtyping.*`.

Relevant `pyright` issue: https://github.com/microsoft/pyright/issues/2277
Note that the core JAX API follows a similar pattern as this PR (marking names public by writing `import X as X`): https://github.com/google/jax/blob/main/jax/__init__.py

Main note: marking things as public only works with the pattern `import X as X` and not `import X as Y`. The alternative is using `__all__`, which I had to do in `array_types.py`. For the `Array` name, I switched the `from jax.numpy import ndarray as Array` to `from jax import Array as Array` to avoid using `__all__`; `ndarray` has just been an alias for a while so hopefully this is ok!

### CODE REVIEW

**Comment by patrick-kidger** [comment]
Hi there! Thanks for the fix, that's really helpful.
- Do we need the `__all__` in `array_types.py`? This module is private to `jaxtyping`, and the expected interface is that end users are only ever accessing things from the base `jaxtyping` namespace.
- Do we need to bump the minimum JAX version in `setup.py` in order to support using `Array`?
- If you bump the version number then I'd be happy to do a new release.

**Comment by brentyi** [comment]
Thanks for the quick response!

- `__all__` in `array_types.py`: yeah, this also looks strange to me, but pyright complains if I don't add it.
    If I comment those lines out:
    ```
    from jaxtyping import Float
    ```
    gives me:
    ```
    "Float" is not exported from module "jaxtyping.array_types"
    Import from "typing_extensions" instead
    ```
- JAX version: I bumped to `0.3.18`, which is when `jax.Array` was introduced: https://github.com/google/jax/releases/tag/jax-v0.3.18
- `setup.py`: bumped this to `0.2.9`!

**Comment by patrick-kidger** [comment]
Hmmm, that's super weird. The `jaxtyping <-> jaxtyping.array_types` interface is private to `jaxtyping`. Your client code should never need to care what convention is followed across that interface.

Do you want to recreate that as a MWE and submit it as an issue to pyright? I doubt it's an actual bug in pyright but I'd like to know what the correct thing to do here is, and perhaps they can offer some guidance. (Certainly I don't see `__all__` statements being used everywhere.)

**Comment by brentyi** [comment]
Yeah, I agree it's a little bit strange. I made a reproduction: https://github.com/brentyi/jaxtyping-export-repro

Will try to make a pyright issue in a bit, but the tldr is that there's some funkiness associated with re-importing an imported name:

`exporttest/src.py`:
```python
from typing import List
from typing import List as Imported

_Assigned = List
```

`exporttest/__init__.py`:
```python
from .src import _Assigned as _Assigned
from .src import Imported as Imported
```

`try_import.py`
```python
from exporttest import _Assigned  # OK
from exporttest import Imported   # Error!
```

**Comment by patrick-kidger** [comment]
Looks like the pre-commit hooks are failing -- isort doesn't like the import style being used. I think it'd probably be best to modify the `.isort.cfg` file to accept the style you used, though.

(Side note, I've just pushed a change that makes JAX an optional dependency -- e.g. to support using jaxtyping with PyTorch, so you'll need to rebase.)

**Comment by patrick-kidger** [comment]
Nice! Merged, and thank you for contributing.

**Pull request merged**
