### PR TITLE
JAX is no longer a hard dependency (to support e.g. PyTorch)

### PR DESCRIPTION
**Pull request by patrick-kidger**

### CODE REVIEW

**Comment by corwinjoy** [comment]
@patrick-kidger 
Awesome! I am so happy to see this / glad you added this! I just got done annotating a big library (linear_operators) with jaxtyping and was about to submit a PR when I saw you had already done it! In doing this, I had a couple of comments for your consideration:

1. It may make sense to add jax as an optional dependency?  In my branch I have this in the setup file:
```
extras_require = {
    'PyTree':  ["jax>=0.3.4"]
}
```
2. I wasn't sure what to do about the tests since these use jax. It looks like you skipped this as well. I think it would be good to be able to run tests without jax installed so that there can be a test this is really working. Maybe it makes sense to convert these to use numpy?  Or create a simple stub for the Array type?

Anyway, thanks again for this update!

**Comment by corwinjoy** [comment]
FYI here is the PR upgrading linear_operator to use jaxtyping:
https://github.com/cornellius-gp/linear_operator/pull/42

**Comment by patrick-kidger** [comment]
I'd like to avoid adding an explicit optional dependency, just to avoid the need for end users to make additional choices. As it is, `Array` and `PyTree` will simply exist if JAX is installed, and not if they aren't.

This doesn't stop you from simply making JAX a requirement as a library author. If you use `PyTree` then just list both JAX and jaxtyping as dependencies.

As for tests -- this was something sufficiently simple that I just didn't want to take the time building out the additional infrastructure for running two sets of tests. If that's important to you then I'd be happy to accept a PR on this: adding numpy/pytorch/tensorflow tests, and updating the CI so that we run the numpy/pytorch/tensorflow tests, followed by installing jax, followed by the JAX tests.

**Comment by corwinjoy** [comment]
Ah OK. That makes sense. I may add some simple numpy/pytorch/tensorflow tests just to have some test cases for the no jax case and have something to test the dimension bindings.

**Pull request merged**
